### ISSUE TITLE
Custom language parameter 

### ISSUE THREAD

**Issue by billydekid** [keensoft/alfresco-simple-ocr#10]
Hi, 
If we checked the log, the tesseract language parameter (-l) was set to eng+spa+fra trained data. 
Could we change to another language library?  If so, how? 
Thanks,

**Comment by angelborroy-ks** [comment]
Please, read [configuration](https://github.com/keensoft/alfresco-simple-ocr#configuration) section.

**Comment by billydekid** [comment]
Ooh thanks! Not properly read it.
