### ISSUE TITLE
Wizard install workaround script in FAQ is buggy

### ISSUE THREAD

**Issue by Coaxial** [keensoft/alfresco-simple-ocr#12]
Thanks for writing the plugin, it works well and will let me digitize all my personal papers! A ton of space saved in the drawers!

I just wanted to point out that [the script](https://github.com/keensoft/alfresco-simple-ocr/wiki/FAQ) for the workaround if you've installed with the wizard is buggy.

Here is a script that does the same thing but more sanely:

```bash
#!/usr/bin/env bash
# set -o xtrace # Uncomment for debugging/troubleshooting

sudo /usr/bin/pdfsandwich "$@"
```

By quoting your variable, you avoid word splitting. For example, if you passed several options as in `-verbose -lang eng+fra` via `ocr.extra.commands`, pdfsandwich would only run with `-verbose` and without `-lang` or anything after if `$@` wasn't quoted.

Also, `sudo` is more sane than `su` because it sanitizes arguments.

Setting the `xtrace` option gives a more verbose output in the logs when the command fail. It's quite helpful when troubleshooting.

**Comment by angelborroy-ks** [comment]
Thanks for your contribution.

The script has been added for users at [https://github.com/keensoft/alfresco-simple-ocr/wiki/FAQ#alternative-to-previous-script](https://github.com/keensoft/alfresco-simple-ocr/wiki/FAQ#alternative-to-previous-script)
