### ISSUE TITLE
Can you manually resubmit a document for OCR?

### ISSUE THREAD

**Issue by coaxial** [keensoft/alfresco-simple-ocr#14]
Rather than deleting it and re-adding it, is there a way to request a document to be OCRed again?

What happens if Alfresco crashes or there is an error while OCRing the document, does it get resubmitted for OCR or is it added to the library without OCR?

**Comment by angelborroy-ks** [comment]
The addon is a simple action, so you can create a rule (re-launching it over a folder) or even you can create a simple JavaScript by using `action` root object to be launched via JavaScript console or so.

But there is no option in Share interface for doing that (by now).

**Comment by tfdsimoes-ks** [comment]
It was created an option to do the action of OCR in release 2.0.0 or higher, check [2.1.0](https://github.com/keensoft/alfresco-simple-ocr/releases/tag/2.1.0)
