### ISSUE TITLE
AttributeError when calling ocrmypdf from script

### ISSUE THREAD

**Issue by wriphaus** [keensoft/alfresco-simple-ocr#15]
When dropping a PDF-file into a folder that has a rule to perform ocr the following errors show up in alfresco.log and catalina.log:

```
2016-09-14 10:55:02,076 INFO  [es.keensoft.alfresco.ocr.OCRTransformWorker] [defaultAsyncAction6] EXIT VALUE: 1
2016-09-14 10:55:02,076 INFO  [es.keensoft.alfresco.ocr.OCRTransformWorker] [defaultAsyncAction6] STDOUT:
2016-09-14 10:55:02,076 INFO  [es.keensoft.alfresco.ocr.OCRTransformWorker] [defaultAsyncAction6] STDERR: Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 7, in <module>
    from ocrmypdf.__main__ import run_pipeline
  File "/usr/lib/python3.4/site-packages/ocrmypdf/__main__.py", line 60, in <module>
    if tesseract.version() < MINIMUM_TESS_VERSION:
  File "/usr/lib64/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/ocrmypdf/tesseract.py", line 57, in version
    tesseract_version = re.match(r'tesseract\s(.+)', versions).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

2016-09-14 10:55:02,076 WARN  [es.keensoft.alfresco.ocr.OCRExtractAction] [defaultAsyncAction6] workspace://SpacesStore/36917a25-024c-4f40-a1d1-fd1d48b23ac3: java.lang.RuntimeException: org.alfresco.service.cmr.repository.ContentIOException: 08140008 Failed to perform OCR transformation:
Execution result:
   os:         Linux
   command:    /opt/alfresco-community/scripts/ocr.sh /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_6082099407754684458.pdf /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_6082099407754684458_ocr.pdf
   succeeded:  false
   exit code:  1
   out:
   err:        Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 7, in <module>
    from ocrmypdf.__main__ import run_pipeline
  File "/usr/lib/python3.4/site-packages/ocrmypdf/__main__.py", line 60, in <module>
    if tesseract.version() < MINIMU
```

The exit code 1 indicates that there is a problem with attributes

We use a script that executes ocrmypdf

```
#!/bin/bash
export PATH=/usr/bin/:$PATH
ocrmypdf --verbose 1 -l deu+eng "$@"
```

If the script or ocrmypdf itself is executed manually, everything works fine and a PDF with ocr is generated.
btw. if the command in the script is executed with "sudo" it runs into anoter error like: 
`err:        sudo: sorry, you must have a tty to run sudo`

ocr-section in alfresco-global.properties looks like this:
```
# OCR Config
ocr.command=/opt/alfresco-community/scripts/ocr.sh
ocr.output.verbose=true
ocr.output.file.prefix.command=
ocr.extra.commands=
ocr.server.os=linux
```

List of installed amps:
```
[root@alfresco alfresco-community]# java -jar ./bin/alfresco-mmt.jar list tomcat/webapps/alfresco
Module 'simple-ocr-repo' installed in 'tomcat/webapps/alfresco'
   -    Title:        simple-ocr-repo Repository AMP project
   -    Version:      1.1.0.1607271657
   -    Install Date: Wed Sep 14 10:38:07 CEST 2016
   -    Description:   Manages the lifecycle of the simple-ocr-repo Repository AMP (Alfresco Module Package)
Module 'org.alfresco.integrations.google.docs' installed in 'tomcat/webapps/alfresco'
   -    Title:        Alfresco / Google Docs Integration
   -    Version:      3.0.3
   -    Install Date: Mon Sep 12 11:05:32 CEST 2016
   -    Description:   The Repository side artifacts of the Alfresco / Google Docs Integration.
Module 'alfresco-aos-module' installed in 'tomcat/webapps/alfresco'
   -    Title:        Alfresco Office Services Module
   -    Version:      1.1
   -    Install Date: Mon Sep 12 11:05:29 CEST 2016
   -    Description:   Allows applications that can talk to a SharePoint server to talk to your Alfresco installation
Module 'alfresco-share-services' installed in 'tomcat/webapps/alfresco'
   -    Title:        Alfresco Share Services AMP
   -    Version:      5.2.0
   -    Install Date: Mon Sep 12 11:05:27 CEST 2016
   -    Description:   Module to be applied to alfresco.war, containing APIs for Alfresco Share
```

System:
centos7.2
Alfresco Community 5.1
ocrmypdf 4.2.4
tesseract 3.04.00
 leptonica-1.72
  libgif 4.1.6(?) : libjpeg 6b (libjpeg-turbo 1.2.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7 : libwebp 0.3.0

Any idea how to solve this?

**Comment by angelborroy-ks** [comment]
It looks like it's using a tesseract version under the minimum required. Have you installed your tesseract 3.0.4 under `usr/bin`?

**Comment by wriphaus** [comment]
Yes it's installed under `/usr/bin`
`tesseract -v` shows version 3.04.00
In `/usr/lib/python3.4/side-packages/ocrmypdf/__main__.py` it says the minimum required version is 3.02.02.
The wired thing ist that you can run it like `ocrmypdf test.pdf testocr.pdf` without any errors.
We supposed that there is something wrong with the parameters because of `exit code:  1` which pints to bad arguments in [http://fossies.org/dox/OCRmyPDF-4.2.1/classocrmypdf_1_1ExitCode.html#a1cc0ace1a8fffcefca37993e470852c8](url)

**Comment by angelborroy-ks** [comment]
Have you seen this one [https://github.com/keensoft/alfresco-simple-ocr/issues/12](https://github.com/keensoft/alfresco-simple-ocr/issues/12)?

**Comment by wriphaus** [comment]
Yea, this post was the reason to try the "script-method" after running into errors when starting ocrmypdf directly from alfresco-global.properties.
Do you think the settings in alfresco-global.properties and the script are correct in my first post?

**Comment by angelborroy-ks** [comment]
can you try to execute that OCR script from command line with the user who is running Alfresco?

**Comment by wriphaus** [comment]
We haven't changed anything in Alfresco, so it should be root, right? Or is it the user "Admin" from Alfresco?
When I run the script like this: 
`./ocr.sh /home/servicepc/test.pdf /home/servicepc/testocr.pdf`
it works.
Same with a "normal" user on this machine.

**Comment by wriphaus** [comment]
We figured out a configuration that works now.
Script looks like this:
```
#!/bin/bash
sudo ocrmypdf --rotate-pages-threshold 7 -r -l deu+eng "$@" 
```
commented out the following line in `/etc/sodoers`
`# Defaults    requiretty`
This avoids the error  `err: sudo: sorry, you must have a tty to run sudo` when using sudo in the script.
Rotation and OCR work fine.

**Comment by angelborroy-ks** [comment]
Congrats!

Thanks for sharing.
