### ISSUE TITLE
Broken link on latest version 1.1.1 (actually is 1.1.0)

### ISSUE THREAD

**Issue by billydekid** [keensoft/alfresco-simple-ocr#16]
Hi,

As shown on readme page that current latest version of **repo AMP** is 1.1.1 which linked to https://github.com/keensoft/alfresco-simple-ocr/releases/download/1.1.1/simple-ocr-repo.amp.

It's a broken link since actually the latest version was 1.1.0 (https://github.com/keensoft/alfresco-simple-ocr/releases).

CMIIW.

Thanks,

**Comment by angelborroy-ks** [comment]
Latest version is now 1.1.1, to use with Alfresco 5.0.d or Alfresco 5.1.g.

Tag has been assigned and release has been created.

Thanks.
