### ISSUE TITLE
Using windows OCR

### ISSUE THREAD

**Issue by miggy4340** [keensoft/alfresco-simple-ocr#17]
Hello Angel.

Can you give some more info on using the windows OCR. 

Reading MS doc I don't see how http://localhost:60064/api/OCR/ is installed and used.

Is there a spécific keensoft install for this. I think a saw something on keensoft blog but my spanish is very limited.

Regards

Bertrand

**Comment by angelborroy-ks** [comment]
Hi,

We are planning to publish our own component at Windows Store, but have not a target date yet.

However, you can use any of the existents or build your own based in https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/OCR 

Thanks

**Comment by fsforna** [comment]
Dear Angel,
have you any news about you last comment? 
Could you write some tips how to create a new Visual Studio project that exposes the local service URL http://localhost:60064/api/OCR/ ?

I had experimented that the OCR made by Windows.OCR lib was really more accurate than pdfsandwich one.

Regards,
Francesco.

**Comment by angelborroy-ks** [comment]
In fact we abandoned that line, so we are not going to release a Windows based service.

You can test also with OCRmyPDF, that can be more accurate than pdfsandwich in some scenarios.
