### ISSUE TITLE
Unable to pass the -tesseract command line option to pdfsandwich

### ISSUE THREAD

**Issue by twilliamsflcss** [keensoft/alfresco-simple-ocr#19]
Attempting to control the processor priority of tesseract with nice. I don't want to limit tesseract, I just don't want it to bring the rest of Alfresco to a halt. 

Method attempted:
alfresco-global.properties:
  ocr.command=/usr/bin/pdfsandwich
  ocr.output.verbose=true
  ocr.output.file.prefix.command=-o
  ocr.extra.commands=-tesseract "nice -n 10 tesseract" -verbose -lang eng
  ocr.server.os=linux

Log after attempt:
Rule applied to folder to trigger OCR of the document added, upon uploading PDF to the folder the logs are as follows:
     os:         Linux
     command:    /usr/bin/pdfsandwich -tesseract "nice -n 10 tesseract" -verbose -lang eng /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_7526164203075376866.pdf -o /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_7526164203075376866_ocr.pdf
     succeeded:  false
     exit code:  2
     out:
     err:        /usr/bin/pdfsandwich: unknown option `-n'.
  USAGE: pdfsandwich [options] inputfile.pdf

If I copy and use the line after "command:" at prompt, it successfully executes the command and "top" reflects the nice priority. How can I pass the "nice -n 10 tesseract" to limit the priority? 

What I've tried so far:
I've moved the (-tesseract "nice -n 10 tesseract") option to the "ocr.command" line and also attempted using a "\\-n" to allow it. 

What else can I do to make this work?

**Comment by angelborroy-ks** [comment]
You can also play with Alfresco async thread pool, by setting following properties at `alfresco-global.properties`

```
# Default Async Action Thread Pool
default.async.action.threadPriority=1
default.async.action.corePoolSize=8
default.async.action.maximumPoolSize=20
```

Anyway, we are planning to support running OCR software in a remote server, so it won't impact in Alfresco server performance. Should be this alternative suitable for you?

**Comment by twilliamsflcss** [comment]
Correct me if I'm wrong:
     If there's 100% CPU and there are 4 threads generated to perform tesseract task, each thread would consume 25%?

     If true then limiting the threads would only change the number of simultaneous tasks. I'd like to limit tesseract ONLY without affecting the rest of Alfresco and it's modules. Is there something specific that prevents the "nice -n" from passing? 

     I may be able to change the "command: /usr/bin/pdfsandwich" to "command: /opt/alfresco-community/scripts/**CustomScript**" Would the script be able to acquire the "${source} AND ${target} values?

**Comment by angelborroy-ks** [comment]
Try this: https://github.com/keensoft/alfresco-simple-ocr/wiki/FAQ

**Comment by twilliamsflcss** [comment]
Confirmed Improvement

Test parameters:
  Uploading ten 5 page PDF documents to a folder with a rule to OCR immediately.

Before Modification:
  During OCR process - web access, webdav access, and smart phone app all suffered greatly, Unusable!

After Modification:
  Durinc OCR process - htop reports full utilization of CPU with about 25 tesseract threads open.
  Attempts to smoothly use web access, webdav, and phone app were all successful during the OCR.

I recommend this action if you're utilizing hardware that doesn't have virtually unlimited processing power. I may look into running the "nice -n 10" command against unpaper and convert as well.
