### ISSUE TITLE
PDFs contain spaces between each character in words so search function won't work

### ISSUE THREAD

**Issue by ibschreiber** [keensoft/alfresco-simple-ocr#20]
Hi,
I'm quite new to the alfresco world. What I wanted to achieve: 
- Scan a Document (as .tiff)
- upload it to Alfresco
- let the magic happen and the document converted to a .pdf
- search for the document by text
What works: 
- All except the search

In the document, the text is selectable but contains a space character between every letter in the words so searching is not working. Any idea how to fix this? I'm using ocrmypdf with --verbose 1 --force-ocr -l deu+eng 

Thank you,
Michael

**Comment by ibschreiber** [comment]
It's a completely different Problem, I'll start a new issue

**Comment by ibschreiber** [comment]
changed it and reopened it. Sorry :-)

**Comment by angelborroy-ks** [comment]
Have you installed all languages for tesseract? 

http://askubuntu.com/questions/793634/how-do-i-install-a-new-language-pack-for-tesseract-on-16-04

**Comment by ibschreiber** [comment]
Hi,
all relevant languages are installed. I found another solution, at least 
for documents I scan to get them into the DMS: It's called VueScan, runs 
on Linux, Mac and well, Windows too (who cares ;-) and comes with built 
in OCR (which works quite well). It costs 90$ and supports my scanner 
(Fujitsu fi-5110C) perfectly.

Still, the actual Problem remains. Any other Idea?

Michael

**Comment by angelborroy-ks** [comment]
Can you please provide a sample TIFF to be OCRd?

I've been testing my own in our servers and it works as expected: searching is allowed inside the document and text is indexed for Alfresco searching also.
