### ISSUE TITLE
Inquiry about Alfresco V5.2

### ISSUE THREAD

**Issue by ppeniaacp** [keensoft/alfresco-simple-ocr#21]
Hello Angel.
I need to know if there is an installer / support for Alfresco V5.2 or if it's near to be released.
Thank you.
Regards.

Pablo

**Comment by angelborroy-ks** [comment]
We have not planned (yet) to test this addon for Alfresco 5.2, but it should work without changes. Have you tried standard installation?

**Comment by ppeniaacp** [comment]
Yes, I´m installing .amp file with documentation of Alfresco in Windows, but it return error Unsupported major.minor version 52.0

**Comment by angelborroy-ks** [comment]
It seems that OCR addon is compiled by using Java 8 (which is recommended JVM by Alfresco). Which Java version are you using?

**Comment by ppeniaacp** [comment]
Ok, I´m working with Java 7. I will try it and tell you. Thank you.

**Comment by tarioch** [comment]
Seems to work fine for me on 5.2

**Comment by stalker83** [comment]
for me it works on 5.2 pretty well too :)
