### ISSUE TITLE
How to install alfresco-simple-ocr in Alfresco 5.1 on Windows 10

### ISSUE THREAD

**Issue by roondal** [keensoft/alfresco-simple-ocr#22]
I'm new in the use of Alfresco i need the OCR, I found how to install AMP file and I did and now I can not log in alfresco, I get error

Your authentication details have not been recognized Alfresco or may not be available at this time.

I use Windows 10 and Alfresco 5.1

Do you have somewhere a complete user's manual how to do OCR implementation in Alfresco. Since I saw that different settings depending on whether it is used pdfsandwich, OCRmyPDF or Windows.OCR, have not been able to install any of it?

I apologize if I ask a lot of questions, I am new in everything and exploring opportunities

**Comment by angelborroy-ks** [comment]
This addon does not work without pdfsandwich, OCRmyPDF or Windows.Media.OCR.

Probably a`alfresco.log` file is including this kind of errors.

On the other hand, installing on Windows requires to develop a local program to wrap Windows.Media.OCR which is not provided by our addon.
