### ISSUE TITLE
Ok for ALF CE 5.1 with -force !

### ISSUE THREAD

**Issue by Archi37** [keensoft/alfresco-simple-ocr#23]
Hi all,
It's ok for me after many test, i has do make this :

java/bin/java -jar bin/alfresco-mmt.jar install amps/simple-ocr-repo-1.1.0.amp tomcat/webapps/alfresco.war -preview **-force**

Cordialy

**Comment by angelborroy-ks** [comment]
It should not be necessary to use **-force**, as no Alfresco resource has been overwritten. I'll check this later.

Thanks

**Comment by Archi37** [comment]
Hi, all it's perfect for me, but after many hours....

Fom TIFF to transform OCR : (Now !)
 2017-01-22 06:38:01,998  INFO  [alfresco.ocr.OCRTransformWorker] [defaultAsyncAction4] STDERR: 
 2017-01-22 06:38:10,843  INFO  [alfresco.ocr.OCRTransformWorker] [defaultAsyncAction5] EXIT VALUE: 0
 2017-01-22 06:38:10,844  INFO  [alfresco.ocr.OCRTransformWorker] [defaultAsyncAction5] STDOUT: pdfsandwich version 0.1.6
Input file: "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_2039738739124311188.pdf"
Output file: "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_2039738739124311188_ocr.pdf"
Number of pages in inputfile: 1
More threads than pages. Using 1 threads instead.
Processing page 1.
identify -format "%w\n%h\n"  "/tmp/pdfsandwich_inputfilef0790b.pdf[0]" 
OCR done. Writing "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_2039738739124311188_ocr.pdf"

/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_2039738739124311188_ocr.pdf generated.

Done.

But before necessary fo make this :

root@:/opt/alfresco-community/common/lib # ln -sf /lib/x86_64-linux-gnu/libz.so.1.2.8 libz.so.1.2.3
root@:/opt/alfresco-community/common/lib # ln -sf /lib/x86_64-linux-gnu/libz.so.1.2.8 libz.so.1.2.8
idem for libjpeg.so......
ln -sf /usr/lib/x86_64-linux-gnu/libjpeg.so.62 libjpeg.so.62.0.0 (<- /opt/alfresco.../common/lib)

anf for end, only this :

# localOCR program
ocr.command=/usr/bin/pdfsandwich
ocr.output.verbose=true
ocr.output.file.prefix.command=-o
# rotating,cleaning,languages…
ocr.extra.commands=-lang fra 
ocr.server.os=linux 

Many thanks for this pluggin - Cordialy
