### ISSUE TITLE
Install and Configuration alfresco-simple-ocr on Alfresco

### ISSUE THREAD

**Issue by tap90** [keensoft/alfresco-simple-ocr#24]
Hi  Angel

Is there any tutorial that shows how to install and configuring correctly the alfresco-simple-ocr plugin?
This link ([http://beecon.buzz/talks/?id=20160125005]) retrieve 404 not found

Thanks in advance

**Comment by mikelasla** [comment]
Hi tap90

That talk took place in beecon 2016 and the beecon website is focused now on the [beecon 2017](http://beecon.buzz/)

The content of the beecon 2016 It's still there but you need to prefix 2016 in the urls and there you have it. 

http://beecon.buzz/2016/talks/?id=20160125005

The link to the presentation is also broken, below the good one

http://beecon.buzz/2016/assets/data/files/20160125005/BeeCon2016_Lightning_20160125005_OCR.pdf

Regards

**Comment by tap90** [comment]
Thank you for your fast reply
