### ISSUE TITLE
alfresco and pdf sandwich on 2 differents servers

### ISSUE THREAD

**Issue by emilie2b** [keensoft/alfresco-simple-ocr#32]
Hi, I try to use this add-on on a windows installation of alfresco with pdf Sandwich on a linux server. 
So I took the linux script provided here [https://angelborroy.wordpress.com/2017/01/19/alfresco-installing-ocr-as-an-external-service/](https://angelborroy.wordpress.com/2017/01/19/alfresco-installing-ocr-as-an-external-service/) and change it to be using on windows, the script works fine alone. But I can't make it work with alfresco and the add-on. Here's my global.properties file:
`ocr.command=E:\test.bat
ocr.output.verbose=true
ocr.output.file.prefix.command=-o

ocr.extra.commands=-verbose -lang eng+fra
ocr.server.os=linux`

At first I had an error that was saying that the host does not exists. I was using a putty saved session so I tried without the saved session and now get a read error (408) .

If I replace `ocr.server.os=linux` with `ocr.server.os=windows` I got java errors like invalid uri as it tries to connect to a web service that doesn't exists because I use pdf sandwich on the linux server, it doesn't try to use the bat script.

Is someone has already try something like this? Is it even possible?

**Comment by emilie2b** [comment]
Finally it works, it was just an issue with the ssh key, tomcat is running as a service with the service account not the admin one, so the key was not in the registry either in pageant for this session. 
The 408 error was because pscp was in a waiting state as it can't log in, so after a while alfresco stop waiting for the response and there is the 408 error.

**Comment by angelborroy-ks** [comment]
Thanks for your feedback.
