### ISSUE TITLE
PDF scanned with simple OCR, but it is not searchable. NO error message. 

### ISSUE THREAD

**Issue by aboyz** [keensoft/alfresco-simple-ocr#33]
`2017-07-16 12:05:54,696 WARN  [es.keensoft.alfresco.ocr.OCRExtractAction] [http-apr-8080-exec-9] workspace://SpacesStore/8baf93bd-102e-4404-b687-2707d0e91a55: Node does not exist: workspace://SpacesStore/8baf93bd-102e-4404-b687-2707d0e91a55 (status:null)
2017-07-16 12:06:11,341 INFO  [es.keensoft.alfresco.ocr.OCRTransformWorker] [http-apr-8080-exec-9] EXIT VALUE: 0
2017-07-16 12:06:11,344 INFO  [es.keensoft.alfresco.ocr.OCRTransformWorker] [http-apr-8080-exec-9] STDOUT: pdfsandwich version 0.1.4
Checking for convert:
convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-04-18 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib

Checking for unpaper:
unpaper -version
6.1
Checking for tesseract:
tesseract -v
Checking for gs:
gs -v
GPL Ghostscript 9.18 (2015-10-05)
Copyright (C) 2015 Artifex Software, Inc.  All rights reserved.
Input file: "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1103660786151459656.pdf"
Output file: "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1103660786151459656_ocr.pdf"
Number of pages in inputfile: 2
More threads than pages. Using 2 threads instead.

Parallel processing with 2 threads started.
Processing page order may differ from original page order.

Processing page 1.
identify -format "%w\n%h\n"  "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1103660786151459656.pdf[0]"
Processing page 2.
identify -format "%w\n%h\n"  "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1103660786151459656.pdf[1]"
convert  -type Bilevel  -density 300x300 "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1103660786151459656.pdf[0]" /tmp/pdfsandwich5ec85c.pbm
convert  -type Bilevel  -density 300x300 "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1103660786151459656.pdf[1]" /tmp/pdfsandwich257aef.pbm
unpaper --overwrite  --no-grayfilter --layout none /tmp/pdfsandwich257aef.pbm /tmp/pdfsandwicha53d7a_unpaper.pbm
unpaper --overwrite  --no-grayfilter --layout none /tmp/pdfsandwich5ec85c.pbm /tmp/pdfsandwich0ec278_unpaper.pbm
Processing sheet #1: /tmp/pdfsandwich257aef.pbm -> /tmp/pdfsandwicha53d7a_unpaper.pbm
tesseract /tmp/pdfsandwicha53d7a_unpaper.pbm /tmp/pdfsandwichc79f63  -l eng pdf
Processing sheet #1: /tmp/pdfsandwich5ec85c.pbm -> /tmp/pdfsandwich0ec278_unpaper.pbm
tesseract /tmp/pdfsandwich0ec278_unpaper.pbm /tmp/pdfsandwich36d95f  -l eng pdf
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dDEVICEWIDTHPOINTS=613 -dDEVICEHEIGHTPOINTS=790 -dPDFFitPage -o /tmp/pdfsandwich1b3ea1.pdf /tmp/pdfsandwich36d95f.pdf
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dDEVICEWIDTHPOINTS=613 -dDEVICEHEIGHTPOINTS=790 -dPDFFitPage -o /tmp/pdfsandwich449b3d.pdf /tmp/pdfsandwichc79f63.pdf
OCR done. Writing "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1103660786151459656_ocr.pdf"
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1103660786151459656_ocr.pdf" /tmp/pdfsandwich1b3ea1.pdf /tmp/pdfsandwich449b3d.pdf

Done.

2017-07-16 12:06:11,344 INFO  [es.keensoft.alfresco.ocr.OCRTransformWorker] [http-apr-8080-exec-9] STDERR: tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.51 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0

[image2 @ 0x12b8600] Encoder did not produce proper pts, making some up.
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
[image2 @ 0x2363600] Encoder did not produce proper pts, making some up.
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
OSD: Weak margin (2.69) for 395 blob text block, but using orientation anyway: 0
OSD: Weak margin (6.59) for 413 blob text block, but using orientation anyway: 0
Detected 8 diacritics

`

**Comment by angelborroy-ks** [comment]
Are you using the last addon GA release? 

https://github.com/keensoft/alfresco-simple-ocr/releases/tag/1.1.1

Which Alfresco version are you using?

**Comment by aboyz** [comment]
yes, i'm using the latest alfresco-simple-ocr 1.1.1 and I'm using the latest version of the alfresco community version. 
http://eu.dl.alfresco.com.s3.amazonaws.com/release/community/201707-build-00028/alfresco-community-installer-201707-linux-x64.bin
This is the build i'm using.

Anyway, I did a fresh installed on ubuntu 16 and i was able to installed everything with no error now. So my problem is here.

I have a .pdf image, I dragged into the shared folder and it excute the OCR script. I tail the /opt/alfresco-community/alfresco.log file I do not see any error. It does what it suppose to do.

I checked the .pdf file being uplaoded and I was able to see in it and highlight the text file. So the OCR is working fine. So in alfreso web portal. I try to do a search on the OCR text keyword but it is not grabbing it. Am I missing a step? Search function not working or the OCR document not being indexed.

Please advise.

**Comment by aboyz** [comment]
this is the alfresco.log
`2017-07-20 17:15:08,923 INFO  [es.keensoft.alfresco.ocr.OCRTransformWorker] [defaultAsyncAction4] EXIT VALUE: 0
2017-07-20 17:15:08,923 INFO  [es.keensoft.alfresco.ocr.OCRTransformWorker] [defaultAsyncAction4] STDOUT: pdfsandwich version 0.1.4
Checking for convert:
convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-05-26 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib

Checking for unpaper:
unpaper -version
6.1
Checking for tesseract:
tesseract -v
Checking for gs:
gs -v
GPL Ghostscript 9.18 (2015-10-05)
Copyright (C) 2015 Artifex Software, Inc.  All rights reserved.
Input file: "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4568321969402038774.pdf"
Output file: "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4568321969402038774_ocr.pdf"
Number of pages in inputfile: 2
More threads than pages. Using 2 threads instead.

Parallel processing with 2 threads started.
Processing page order may differ from original page order.

Processing page 1.
Processing page 2.
identify -format "%w\n%h\n"  "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4568321969402038774.pdf[0]"
identify -format "%w\n%h\n"  "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4568321969402038774.pdf[1]"
convert  -type Bilevel  -density 300x300 "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4568321969402038774.pdf[1]" /tmp/pdfsandwich209af7.pbm
convert  -type Bilevel  -density 300x300 "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4568321969402038774.pdf[0]" /tmp/pdfsandwich5dd849.pbm
unpaper --overwrite  --no-grayfilter --layout none /tmp/pdfsandwich209af7.pbm /tmp/pdfsandwiche24e67_unpaper.pbm
unpaper --overwrite  --no-grayfilter --layout none /tmp/pdfsandwich5dd849.pbm /tmp/pdfsandwich4052eb_unpaper.pbm
Processing sheet #1: /tmp/pdfsandwich209af7.pbm -> /tmp/pdfsandwiche24e67_unpaper.pbm
tesseract /tmp/pdfsandwiche24e67_unpaper.pbm /tmp/pdfsandwich355042  -l eng pdf
Processing sheet #1: /tmp/pdfsandwich5dd849.pbm -> /tmp/pdfsandwich4052eb_unpaper.pbm
tesseract /tmp/pdfsandwich4052eb_unpaper.pbm /tmp/pdfsandwich02e628  -l eng pdf
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dDEVICEWIDTHPOINTS=613 -dDEVICEHEIGHTPOINTS=790 -dPDFFitPage -o /tmp/pdfsandwichdc9abc.pdf /tmp/pdfsandwich02e628.pdf
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dDEVICEWIDTHPOINTS=613 -dDEVICEHEIGHTPOINTS=790 -dPDFFitPage -o /tmp/pdfsandwicha0b4ec.pdf /tmp/pdfsandwich355042.pdf
OCR done. Writing "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4568321969402038774_ocr.pdf"
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_4568321969402038774_ocr.pdf" /tmp/pdfsandwichdc9abc.pdf /tmp/pdfsandwicha0b4ec.pdf

Done.

2017-07-20 17:15:08,924 INFO  [es.keensoft.alfresco.ocr.OCRTransformWorker] [defaultAsyncAction4] STDERR: tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0

[image2 @ 0x11e0840] Encoder did not produce proper pts, making some up.
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
[image2 @ 0x115e840] Encoder did not produce proper pts, making some up.
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
OSD: Weak margin (2.69) for 395 blob text block, but using orientation anyway: 0
OSD: Weak margin (6.59) for 413 blob text block, but using orientation anyway: 0
Detected 8 diacritics
`

This is my ocr.sh script
root@ubuntu:/opt/alfresco-community/scripts# more ocr.sh
`export PATH=/usr/bin:$PATH
pdfsandwich $@
`
this is my alfresco-global-properties
`#OCR
ocr.command=/opt/alfresco-community/scripts/ocr.sh
ocr.output.verbose=true
ocr.output.file.prefix.command=-o
ocr.extra.commands=-verbose -lang eng
ocr.server.os=linux
img.root=/usr/share/doc/imagemagick
img.exe=/usr/bin/convert
img.config=${img.root}
img.coders=/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders
img.dyn=/usr/share/ghostscript/9.18/lib
img.gslib=/usr/share/ghostscript/9.18/lib
`
Please let me know what i'm doing is correct. I think i'm missing one more step is to index the OCR file so it'll be searchable.

**Comment by angelborroy-ks** [comment]
Are you using documents in English or they are written in any other language?

**Comment by aboyz** [comment]
I am using document in english only.. all document are in english. is my setting look right?

**Comment by aboyz** [comment]
do you have a skype account or chat program we can chat. I'm willing to pay you to set this up correctly. I properly just need an hour of our time. please provide info so i can contact you.

**Comment by angelborroy-ks** [comment]
Sorry, we are not providing such kind of assistance. In any case, it looks like your OCR is working fine. Probably there is an indexing problem with SOLR.

**Comment by aboyz** [comment]
firgured it out.. libreoffice wasn't running
