### ISSUE TITLE
no bean named 'ocr-extract' is defined 

### ISSUE THREAD

**Issue by koebln** [keensoft/alfresco-simple-ocr#39]
I used Alfresco CE 201702 with simple-ocr 1.1.1 and everything worked fine.

Now I want to switch to Alfresco CE 201707 with simple-ocr 2.3.1 and get an error using the Action in the Document Browser. alfresco.log says:

` ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-7] Exception from executeScript: 08160000 Wrapped Exception (with status template): No bean named 'ocr-extract' is defined`

share.log says:

`simple-ocr-repo Platform Jar Module - SDK 3, 2.3.1, Platform JAR Module (to be included in the alfresco.war) - SDK 3`
`simple-ocr-share Share Jar Module - SDK 3, 2.3.1, Share JAR Module (to be included in the share.war) - SDK 3`

My alfresco-global.properties includes:

```
###Simple OCR Action Properties
#local	ocr program
#ocr.command uses a Shell-Script, to get the right Python environment.
ocr.command=/usr/local/bin/alfocr
ocr.output.verbose=true
ocr.output.file.prefix.command=
#rotating, cleaning, languages…
ocr.extra.commands=--verbose 1 --force-ocr -l deu -c -d
ocr.server.os=linux
```

/usr/local/bin/alfocr:

```
#!/usr/bin/env bash
#set -o xtrace # Uncomment for debugging/troubleshooting

sudo -u andreas /usr/bin/ocrmypdf "$@"
```

Are there any other dependencies or what is going wrong?

**Comment by angelborroy-ks** [comment]
It looks like you had a simple-ocr-1.1.1 already installed. 

If so, you have to uninstall this version with **alfresco-mmt.jar**, remove the AMP file from `amps` directory and re-start the server.

**Comment by koebln** [comment]
Thank you for your quick response. 

Simple-ocr-1.1.1 was installed on the old Installation with Alfresco CE 201702. 
An Upgrade of Alfresco CE is always a new Installation with adding the existing data afterwards. 

So I made a new installation of Alfresco CE 201707 and added simple-ocr-2.3.1 on that. The Test was without adding the existing data, so no simple-ocr-1.1.1 was installed on that new Alfresco instance.

Thank you for your help anyway.

**Comment by angelborroy-ks** [comment]
I've installed on a brand new CE 201707 with following steps.

```
$ cd /opt/alfresco

$ wget https://github.com/keensoft/alfresco-simple-ocr/releases/download/2.3.1/simple-ocr-repo-2.3.1.jar
$ wget https://github.com/keensoft/alfresco-simple-ocr/releases/download/2.3.1/simple-ocr-share-2.3.1.jar

$ mkdir modules/platform
$ mv simple-ocr-repo-2.3.1.jar modules/platform/simple-ocr-repo.2.3.1.jar
$ mv simple-ocr-share-2.3.1.jar modules/share/simple-ocr-share.2.3.1.jar

$ vi tomcat/shared/classes/alfresco-global.properties

ocr.command=/usr/bin/pdfsandwich
ocr.output.verbose=true
ocr.output.file.prefix.command=-o

ocr.extra.commands=-verbose -lang spa+eng+fra
ocr.server.os=linux

$ ./alfresco.sh start
```
I hope this helps.

**Comment by koebln** [comment]
I got it working. The problem was, that the directory `modules/platform` did not exist and I put both .jar-files into the directory `modules/share`.
It was not clear for me, that they had to be in different directories and that the missing directory `modules/platform` must be created. 
Thank you for your help, Simple-OCR is a great tool for working with Alfresco.
