### ISSUE TITLE
Custom indicator on Share for OCRd PDFs

### ISSUE THREAD

**Issue by douglascrp** [keensoft/alfresco-simple-ocr#4]
How about creating a custom indicator for OCRd PDFs?
I think that would make easier to users to identify when the process was successfully executed.

I can work on it if you agree with the idea.

**Comment by angelborroy-ks** [comment]
It's just an evaluator and an indicator, but it requires to start with "share" part: exposing metadata, exposing action,...

I've planned to add some indicator to searchable PDFs (coming from OCRd process or not), but it's not so easy to detect this condition.

**Comment by douglascrp** [comment]
Yes, that's what I thought.
But my idea was to simply expose that the document has been processed by the addon, and not by external OCR.
Of course, if that is possible, it would be something even better.

**Comment by chris001** [comment]
You could just detect whether there's the text layer the graphic layer of under every page, and when there is, activate the custom indicator.  However depending on the code, it could produce a false positive, because there can always be text layers of form input text, notes, annotations, etc.

**Comment by tfdsimoes-ks** [comment]
This is resolved in the release [2.0.0](https://github.com/keensoft/alfresco-simple-ocr/releases/tag/2.0.0)
