### ISSUE TITLE
Cannot find ocr file

### ISSUE THREAD

**Issue by stanzinofree** [keensoft/alfresco-simple-ocr#40]
I copied two jars in bitnami vistual machine folder, I configure the alfresco-global.properties files and configured to use pdfsandwich.
I launch ocr action from action menù and i see that in Alfresco /tmp folder the OCRTransformWorker pdf file is created but I cannot see them in web interface, is there I missing? where can I read the log to view the problem?

**Comment by stanzinofree** [comment]
I find that log is in catalina.out, the error (that I don't have when I run the same command from bash) is:

> err: Fatal error: exception Failure("Could not find program convert. Make sure this program exists and can be found in your search path.)

Do you know I can resolve this?
Thank you

**Comment by angelborroy-ks** [comment]
Is `pdfsandwich` working from command line?
Is it installed at `/usr/local/bin` directory?

**Comment by stanzinofree** [comment]
I solved my problem following instructions at this link: https://github.com/keensoft/alfresco-simple-ocr/issues/5#issuecomment-207097080
My ocr.sh script is now:
`
export PATH=/usr/local/bin:/opt/bitnami/common/bin:/opt/bitnami/common/lib:$PATH
pdfsandwich $@
`
Now it can find the right command and produce the ocr.
