### ISSUE TITLE
Unable to include a rule on a folder by selecting ocr-extract action

### ISSUE THREAD

**Issue by Scamby** [keensoft/alfresco-simple-ocr#41]
Alfresco community has been installed on Ubuntu 17.10 in /home/administrator/alfresco-community, pdfsandwich has been installed (version command works), changes have been made in alfresco-global.properties as indicated in the readme and jar files have been copied to /home/administrator/alfresco-community/modules/share and /repo.  I created a Test OCR folder in my site and attempted to add a rule as directed.  The ocr-extract action is not available for me to select.

/usr/bin/pdfsandwich -version
pdfsandwich version 0.1.6

### PDFSandwich OCR Settings ###

ocr.command=/usr/bin/pdfsandwich
ocr.output.verbose=true
ocr.output.file.prefix.command=-o

ocr.extra.commands=-verbose -lang eng+spa+fra
ocr.server.os=linux

**Comment by angelborroy-ks** [comment]
It's called "Extract OCR", isn't it?

**Comment by Scamby** [comment]
Not seeing that either;

![image](https://user-images.githubusercontent.com/33733760/32915317-740f6d38-cae6-11e7-81db-3d74409e83cf.png)
![image](https://user-images.githubusercontent.com/33733760/32915366-9e2f5272-cae6-11e7-8893-e1ca67b62b9e.png)

Do I just need to copy the jar files (not extract them) into the share and repo locations or somewhere else?  Do I need to do anything else for Alfresco to load them?

**Comment by angelborroy-ks** [comment]
I've guessed you re-started Alfresco after copy the JAR files to target folders, right?

**Comment by Scamby** [comment]
Yes.  I had gotten it to work on another test server about a year or more ago but that was using the amp file.  On this new server the share folder was already there but I had to create the repo folder under /home/administrator/alfresco-community/modules.

**Comment by angelborroy-ks** [comment]
Is this a new installation or an upgrading from previous Alfresco installation? Did you use Alfresco installer or are you installing from scratch?

**Comment by Scamby** [comment]
New install.  Installed Ubuntu than downloaded Alfresco installer and ran that.  Took defaults all the way through.  Then downloaded pdfsandwich deb file and installed.  Then downloaded and copied your jar files.

**Comment by angelborroy-ks** [comment]
Now I see... It's not "repo", it's "platform". The name under the "modules" folder.
Check the right name at /home/administrator/alfresco-community/tomcat/conf/Catalina/localhost/alfresco.xml

**Comment by Scamby** [comment]
That fixed it.  Thanks.
