### ISSUE TITLE
Uninstall simple-ocr 2.3.1

### ISSUE THREAD

**Issue by billydekid** [keensoft/alfresco-simple-ocr#48]
Hi Angel,
How the proper way to uninstall simple-ocr 2.3.1?

Thanks,

**Comment by angelborroy-ks** [comment]
It' a common repo & share Alfresco SDK JAR module: just remove JARS from "module" installation folder and clean up your Alfresco properties file.

**Comment by angelborroy-ks** [comment]
This is also an Alfresco standard operation: downgrading modules is not supported by default.

And even more, Alfresco does not consider this operation as an issue: https://issues.alfresco.com/jira/browse/ALF-20984

Anyway, you can use alternatives ways to perform a module downgrading: http://sujayopillai.com/2016/08/04/update-amp-version.html

**Comment by billydekid** [comment]
Thanks, Angel!
