### ISSUE TITLE
Plugin is not working with multi-tenant environment

### ISSUE THREAD

**Issue by hoangclinh** [keensoft/alfresco-simple-ocr#49]
## BUG
OCR error on Multi-tenant Environment.
### Expected behavior
When i upload a pdffile galon.pdf in tenant (admin@xyz.com)-->click OCR on menu --> OCR file result is created.
### Actual behavior
When i upload a pdffile galon.pdf in tenant (admin@xyz.com)-->click OCR on menu --> OCR file result is not created. 

### Steps to reproduce the behavior
- Install Alfresco, Tesseract, PDFsandwitch, alfresco-simple-ocr
- Create tenant
- Upload PDF test file then OCR

### Additional details (analysis so far, log statements, references, etc.)
Error log in attach file

### Tell us about your environment
Centos 7 64bit + Tesseract 3.05 or 4.0 + PDF sandwitch 0.1.6, alfresco-simple-ocr orig 
[ocr_error.txt](https://github.com/keensoft/alfresco-simple-ocr/files/2153147/ocr_error.txt)
jar file

**Comment by mikelasla** [comment]
Hi,
We haven't tested on multi-tenant enviroment, thanks for reporting.
