### ISSUE TITLE
Upload new version of document doesn't execute OCR process

### ISSUE THREAD

**Issue by billydekid** [keensoft/alfresco-simple-ocr#53]
Hi,
I have a rule which will trigger Extract OCR when document/content uploaded and updated (2 requirements in single rule).

When a new document uploaded (plain PDF), the version will update to 1.1 (OCR runs normally).
But secondly, when I upload new version the OCR process didn't work.

What's and where's the problem?

Thank you,

**Comment by angelborroy-ks** [comment]
I've tested a rule like following:

```
OCR

Description:
Active
Run in background
Rule applied to subfolders

When:
Items are created or enter this folder
Items are updated
 
If all criteria are met:
All Items
 
Perform Action:
Extract OCR
```

And it works as expected.

It has been tested with 2.3.1 release.

**Comment by billydekid** [comment]
Forgot to mention:

```
'simple-ocr-repo' version 1.1.1.1609250928

Alfresco Community v5.2.0
(re21f2be5-b22) schema 10057
```

I've never successful installing 2.3.1 release on Alfresco 5.2.0  :(
(Ubuntu 16.04, pdfsandwich)

**Comment by angelborroy-ks** [comment]
Probably 1.1.1 has this issue, but we're not going to fix that.

2.3.1 is working for Alfresco 5.2: try with a brand new Alfresco in order to identify what's the problem with your current Alfresco server.

**Comment by billydekid** [comment]
What OS version do you use?
I use Ubuntu 16.04

My problem was I posted here: https://github.com/keensoft/alfresco-simple-ocr/issues/47
Similar problem with: https://community.alfresco.com/thread/232405-simple-ocr-alfresco

**Comment by billydekid** [comment]
Problem solved after I build from source code on Ubuntu 16.04.
Thanks @angelborroy !
