### ISSUE TITLE
Update file .PDF

### ISSUE THREAD

**Issue by marcogianini** [keensoft/alfresco-simple-ocr#59]
Hello angel

### Tell us about your environment
My environment:
CentOS 7
Alfresco 5.2
PDFSandwich 0.1.7
Tesseract 4.0.0

## FEATURE / ENHANCEMENT
I noticed that the OCR runs in a PDF and updates it, not keeping the original file.
Is there any way to keep the two files or is it some mistake I'm making?

In other test environment I was used Ubuntu 16.04 with OCRmyPDF and the addons create 2 files in Alfresco Share. But only wiht rules. Doesn´t exist action in version of addons. 

I wolud like to keep this procedure.

Is there possible?

Thanks

**Comment by angelborroy** [comment]
Currently original file is stored as a version, so you keep all the history.

You may modify the source code or create a new rule to make a copy if the original file.

**Comment by marcogianini** [comment]
Thanks Angel.
