### ISSUE TITLE
action not visible

### ISSUE THREAD

**Issue by andreklug** [keensoft/alfresco-simple-ocr#6]
Hi,

I cannot see the action in the folder actions / rules. I did the following to install:

- setup OCRmyPDF

- `# java -jar alfresco-mmt.jar install /home/andre/simple-ocr-repo.amp /opt/alfresco/addons/war/share.war -verbose
Installing AMP '/home/andre/simple-ocr-repo.amp' into WAR '/opt/alfresco/addons/war/share.war'
Backing up WAR file...
WAR has been backed up to '/opt/alfresco/addons/war/share.war-1460411326904.bak'
Adding files relating to version '1.0.0.1604041237' of module 'simple-ocr-repo'
   - File '/WEB-INF/lib/simple-ocr-repo.jar' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/bootstrap-context.xml' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/model-context.xml' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/service-context.xml' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context' added to war
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_es.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_pt.properties' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages' added to war
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/model/ocr-model.xml' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo/model' added to war
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/alfresco-global.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/log4j.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/module-context.xml' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo' added to war
root@alfresco:/opt/alfresco/addons# service alfresco restart
`
- added the code to alfresco-global.properties

Did I miss something? Version is CE 5.1

thank you!

**Comment by angelborroy-ks** [comment]
It's a repo module.

Please uninstall from `share.war` and install in `alfresco.war`

**Comment by andreklug** [comment]
That's what I did first. Now I have restored the share.war file and still do not see the action (after restarting alfresco of course)

And I am a little bit confused by "ready-to-deploy-plugin" vs. "Building the artifacts". I read this that building the artifacts is an alternative to using the amp file. Is that correct?
Also, my UI is in german, and I see that the amp contains EN / PT files (and one without language name), could that be an issue?

Thank you!

**Comment by angelborroy-ks** [comment]
"ready-to-deploy-plugin" is the AMP artifact builded. 
"Building the artifacts" is how to build an AMP artifact.

That file without language name is picked if no locale properties file is detected, so this is no an issue.

Check your `catalina.out` file when starting Alfresco to identify the problem.

**Comment by andreklug** [comment]
I have attached todays catalina log, cannot see anything related. I believe that the log level is set to FINE but am not sure which of these files is used:

/usr/lib/jvm/java-8-oracle/jre/lib/logging.properties
/opt/alfresco/tomcat/conf/logging.properties
/opt/alfresco/tomcat/apache-tomcat-7.0.68/conf/logging.properties
/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/classes/logging.properties

[catalina.2016-04-12.log.zip](https://github.com/keensoft/alfresco-simple-ocr/files/214698/catalina.2016-04-12.log.zip)

**Comment by angelborroy-ks** [comment]
If you can't see a line like this one 

```
2016-03-22 09:47:59,803  INFO  [repo.module.ModuleServiceImpl] [localhost-startStop-1] Starting module 'simple-ocr-repo' version 1.0.1603161659.
```

in your `catalina.out` this module has not been installed. 

Please, review documentation from Alfresco on deploying AMP artifacts: http://docs.alfresco.com/community/concepts/dev-extensions-modules-management-tool.html

**Comment by andreklug** [comment]
i've followed the doc you linked:

`java -jar alfresco-mmt.jar list /opt/alfresco/addons/war/alfresco.war
Module 'simple-ocr-repo' installed in '/opt/alfresco/addons/war/alfresco.war'
   -    Title:        simple-ocr-repo Repository AMP project
   -    Version:      1.0.0.1604041237
   -    Install Date: Mon Apr 11 20:13:21 CEST 2016
   -    Description:   Manages the lifecycle of the simple-ocr-repo Repository AMP (Alfresco Module Package)
Module 'alfresco-share-services' installed in '/opt/alfresco/addons/war/alfresco.war'
   -    Title:        Alfresco Share Services AMP
   -    Version:      5.1.0
   -    Install Date: Tue Feb 16 18:59:47 CET 2016
   -    Description:   Module to be applied to alfresco.war, containing APIs for Alfresco Share`

now I uninstalled and reinstalled the AMP:

`root@alfresco:/opt/alfresco/addons# java -jar alfresco-mmt.jar uninstall simple-ocr-repo /opt/alfresco/addons/war/alfresco.war -verbose
   - Removing file '/WEB-INF/lib/simple-ocr-repo.jar' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/bootstrap-context.xml' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/model-context.xml' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/service-context.xml' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo.properties' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_es.properties' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_pt.properties' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/model/ocr-model.xml' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/alfresco-global.properties' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/log4j.properties' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/module-context.xml' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/model' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/modifications.install' from war
   - Removing file '/WEB-INF/classes/alfresco/module/simple-ocr-repo/module.properties' from war
root@alfresco:/opt/alfresco/addons# java -jar alfresco-mmt.jar install /home/andre/simple-ocr-repo.amp /opt/alfresco/addons/war/alfresco.war -verbose
Installing AMP '/home/andre/simple-ocr-repo.amp' into WAR '/opt/alfresco/addons/war/alfresco.war'
Backing up WAR file...
WAR has been backed up to '/opt/alfresco/addons/war/alfresco.war-1460458277888.bak'
Adding files relating to version '1.0.0.1604041237' of module 'simple-ocr-repo'
   - File '/WEB-INF/lib/simple-ocr-repo.jar' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/bootstrap-context.xml' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/model-context.xml' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/service-context.xml' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context' added to war
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_es.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_pt.properties' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages' added to war
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/model/ocr-model.xml' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo/model' added to war
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/alfresco-global.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/log4j.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/module-context.xml' added to war from amp
root@alfresco:/opt/alfresco/addons# reboot

An alle Benutzer verteilte Nachricht von andre@alfresco
	(/dev/pts/0) um 12:51 ...

Das System wird sich JETZT zum Neustarten herunterfahren!
root@alfresco:/opt/alfresco/addons# Connection to alfresco.home closed by remote host.
Connection to alfresco.home closed.
`
Still no luck.

Would it be useful if I uploaded my alfresco.war so you can have a look at it?

**Comment by angelborroy-ks** [comment]
Yes, please: upload your WAR to any external platform.

**Comment by andreklug** [comment]
It's here: https://www.dropbox.com/s/rkw225qvbc73os4/alfresco.war?dl=0

Please let me know when i can remove the file. And thank you very much for your support!

**Comment by angelborroy-ks** [comment]
It's working for me with your WAR.

`Folder > Manage Rules > Create Rules`

```
New Rule
Name: Test OCR
Description:
Define Rule
When:
 If all criteria are met:
 Unless all criteria are met:
Perform Action:
Extract OCR - Continue on error
```

**Comment by andreklug** [comment]
It doesn't show up here, i tried different browsers and OS.

Are there any other actions that have to be performed following the steps above? Can I check something else? 

![bildschirmfoto 2016-04-12 um 13 39 07](https://cloud.githubusercontent.com/assets/13343357/14458793/f506f982-00b3-11e6-8b0a-f9af1aa18eb9.png)

**Comment by angelborroy-ks** [comment]
I've created a new version including German messages.

Please, try with this one: https://github.com/keensoft/alfresco-simple-ocr/releases/tag/1.0.1

**Comment by andreklug** [comment]
no difference. Does this point to something?

INFO: Deploying web application archive /opt/alfresco/tomcat/webapps/alfresco.war

Apr 12, 2016 1:48:55 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.

**Comment by angelborroy-ks** [comment]
I've discarded all my assumptions. I think I can't help you from this point.

**Comment by andreklug** [comment]
Thank you. I'll try with a fresh installation of Alfresco, if they haven't got any hint in the forums.

**Comment by angelborroy** [comment]
I've been reading Alfresco forum post also.

We are missing something: this should be more easy than this. 

On your deployed Alfresco webapp for the running Tomcat instance, you can find this path: `opt/alfresco-5.1.e/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/simple-ocr-repo/modifications.install`?

**Comment by andreklug** [comment]
No, this path is not there, depending on the installation method it's either /opt/alfresco/ or /opt/alfresco-community/

Even inside this, both variants differ., for example where they put the .war files. i have attached two files which contain the path structure of the installs.
[directories.zip](https://github.com/keensoft/alfresco-simple-ocr/files/217749/directories.zip)

**Comment by andreklug** [comment]
Ah sorry, that maybe did not answer your question. no, these directories are not there. I have 
/opt/alfresco-community/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/ but then only
alfresco-aos-module/                   alfresco-share-services/               org.alfresco.integrations.google.docs/

**Comment by angelborroy-ks** [comment]
```bash
# service alfresco stop

# cp /home/andre/simple-ocr-repo.amp /opt/alfresco-community/amps
# /opt/alfresco-community/appy_amps.sh 

# service alfresco start
```

This must work and your deployed alfresco folder inside webapps should include simple-ocr-repo module folder.

**Comment by andreklug** [comment]
... aaand there it is :) great, thank you!
