### ISSUE TITLE
Can't login anymore after installing the AMP

### ISSUE THREAD

**Issue by ninaran** [keensoft/alfresco-simple-ocr#9]
Hi,

I'm new with Alfresco and this is the first amp I install. 

It's running on an Ubuntu 16.04 server and I'm connecting from a remote windows 7 machine. I installed the amp using the following command:

java -jar alfresco-mmt.jar install /var/dms/alfresco/simple-ocr-repo-deu.amp /var/alfresco-community/tomcat/webapps/alfresco.war -verbose

(it's called simple-ocr-repo-deu.amp since I renamed it. It's the most recent German version you uploaded. i tried with regular simple-ocr-repo-1.1.0.amp too, to no avail)

I get a whole lot of "File '/WEB-INF/classes/....' added to war from amp" messages and no error. But when I restart the alfresco.sh, I'm not seeing the module as active.

However when I use the /bin/apply_amps.sh script, it installs 7 modules ("simple-ocr-repo", "org_alfresco_module_wcmquickstart", "org.alfresco.integrations.google.docs", "alfresco-share-services", "alfresco-aos-module", "org.alfresco.integrations.share.google.doc" and "org_alfresco_module_wcmquickstartshare") to alfresco.war

And if I do that, the login on <ip-adress>/share no longer works..

**Comment by angelborroy-ks** [comment]
Can you include some error detail from your `catalina.out`?

**Comment by ninaran** [comment]
Sure! I made a pastebin for it so that it won't clutter this page. 
Not entirely sure what to look for so I just uploaded the [whole thing](http://pastebin.com/ACKug1kY), I hope that's okay.

Also, I'm trying to connect it with a PDFSandwich.

**Comment by angelborroy-ks** [comment]
You have to include, at least, that property value (`ocr.output.verbose`) in your `alfresco-global.properties` file:

```
Caused by: java.lang.IllegalArgumentException: Invalid boolean value [${ocr.output.verbose}]
	at org.springframework.beans.propertyeditors.CustomBooleanEditor.setAsText(CustomBooleanEditor.java:125)
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:455)
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:427)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:181)
	at org.springframework.beans.BeanWrapperImpl.convertIfNecessary(BeanWrapperImpl.java:449)
	... 43 more
```

**Comment by ninaran** [comment]
Ohh, I didn't change any alfresco-global.properties.

Since I'll be using PDFSandwich, I'll just have to uncomment the lines
 ocr.command=/usr/local/bin/pdfsandwich
 ocr.output.verbose=true
 ocr.output.file.prefix.command=-o

 ocr.extra.commands=-verbose -lang spa+eng+fra
 ocr.server.os=linux

in /var/alfresco-community/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/simple-ocr-repo/alfresco-global.properties , correct?

**Comment by angelborroy-ks** [comment]
It's a better strategy to modify only `/var/alfresco-community/tomcat/shared/classes/alfresco-global.properties`. You can include these values there and leave deployed module untouched. 
This file is shared by all installed modules.

**Comment by ninaran** [comment]
Alright, sweet. I added those five lines and can log in again. 

Aaaand I can create a folder rule to "Use OCR". Now I'll just have to figure out how to use that, but I hope I can do that myself. :)

**Comment by ninaran** [comment]
Hi,
sorry it's me again, hope I'm not annoying you too much. :(

I can now set the rule to extract OCR from elements in a folder.

![ocr_rule_setup](https://cloud.githubusercontent.com/assets/20947541/17580374/72f1ef8e-5f9e-11e6-83a1-ca90fadf6bc8.JPG)

However, nothing seems to happen when I upload a PDF in the folder. Checking the alfresco.log produces [this](http://pastebin.com/rxNyQ3Y3) output.

The line `
Fatal error: exception Sys_error("/tmp/pdfsandwich6c6297.pdf: No such file or directory")` to me seems to indicate that the program has trouble with the line `mv "/tmp/pdfsandwich6c6297.pdf" "/var/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_2720424253749889894_ocr.pdf"`

Or am I missing something else?

**Comment by angelborroy-ks** [comment]
Can you include more error trace from your `catalina.out`?

**Comment by ninaran** [comment]
It seems I keep looking at the wrong spots.. I'm bad at this.

[Here's](http://pastebin.com/tuTzSDUR) the lines in catalina.out from today. I'm seeing the same snippet at the very bottom as in alfresco.log, not sure if that's the cause though.

**Comment by angelborroy-ks** [comment]
Ghostscript 9 is required, but you're using 8.64:

```
gs -v
GPL Ghostscript 8.64 (2009-02-03)

```

Check the [FAQ](https://github.com/keensoft/alfresco-simple-ocr/wiki/FAQ) or some [closed issues](https://github.com/keensoft/alfresco-simple-ocr/issues/5), where different alternatives for installation are exposed.

**Comment by ninaran** [comment]
And here I thought I could circumvent that problem by simply uninstalling ghostscript and installing just the most recent version after installing alfresco. Ah well damn, no idea where that old version came from.

However even with Ghostscript 9.18 the [error](http://pastebin.com/eqpcJYfx) persists.

**Comment by angelborroy-ks** [comment]
If you used default installer to install Alfresco, then you can use the method described in the [FAQ](https://github.com/keensoft/alfresco-simple-ocr/wiki/FAQ).
 
If you decide to re-install Alfresco from scratch, you can follow some of the alternatives provided in that [Issue](https://github.com/keensoft/alfresco-simple-ocr/issues/5).

While a log including "Ghostscript 8.64" appears in your `catalina.out`, the addon won't run.

**Comment by ninaran** [comment]
Okay I did a complete re-install from scratch.
My steps:

1. Install Alfresco, `./alfresco-community-installer-201605-linux-x64.bin`
2. Install the components "Java", "PostgreSQL", "LibreOffice", "Solr4", "Alfresco Office Services", "Web Quick Start" and "Integration of Google Docs"
3. Move the "simple-ocr-repo-deu.amp" to /var/alfresco-community/amps
4. Install the amp, `java -jar alfresco-mmt.jar install /var/alfresco-community/amps/simple-ocr-repo-deu.amp /var/alfresco-community/tomcat/webapps/alfresco.war -verbose`
5. Create the script /var/alfresco-community/scripts/ocr.sh and make it executable, 
`#!/bin/bash
export PATH=/usr/bin/:$PATH
pdfsandwich $@`
6. Edit /var/alfresco-community/tomcat/shared/classes/alfresco-global.properties in the following ways:
 `#img.root=/var/alfresco-community/common
 #img.dyn=${img.root}/lib
 #img.exe=${img.root}/bin/convert
 img.root=/usr/share/doc/imagemagick
 img.exe=/usr/bin/convert
 img.config=${img.root}
 img.gslib=/usr/share/ghostscript/9.18/lib

 ocr.command=/var/alfresco-community/scripts/ocr.sh
 ocr.output.verbose=true
 ocr.output.file.prefix.command=-o
 ocr.extra.commands=-verbose -lang spa+eng+fra+deu
 ocr.server.os=linux`
7. Start Alfresco

Now, I can still see the rule when I create/edit a folder, however there's still the issue of nothing happening and catalina.out displaying the error
`Fatal error: exception Sys_error("/tmp/pdfsandwichb43354.pdf: No such file or directory")`

[Here's](http://pastebin.com/F7Y79peh) the catalina with literally everything that has happened so far on the fresh install.

**Comment by angelborroy-ks** [comment]
It should work. 

Can you try with [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF)?

**Comment by ninaran** [comment]
Yeah, I'll try with that. I didn't want to, due to the readme saying Ubuntu 16.10+ and me only using 16.04, but I'll give it a shot and report back.

**Comment by ninaran** [comment]
Alright so, now:
1. I installed OCRmyPDF via `pip3 install ocrmypdf `
2. Stopped Alfresco Server
3. Changed `/var/alfresco-community/tomcat/shared/classes/alfresco-global.properties` to:
> ocr.command=/usr/local/bin/ocrmypdf
> ocr.output.verbose=true
> ocr.output.file.prefix.command=
> ocr.extra.commands=--verbose 1 --force-ocr -l spa+eng+fra+deu
> ocr.server.os=linux
I also changed the img.<stuff> settings back to default.
4. Start Alfresco Server
5. Create a new folder with the "Extract OCR" rule in the background when anything is dropped in it

And now I'm getting some really nasty [errors](http://pastebin.com/QY4mg632).

**Comment by angelborroy-ks** [comment]
Can you check if `pdfsandwich` and `ocrmypdf` work properly from command line? 
Without using Alfresco integration.

**Comment by ninaran** [comment]
Good call. 
OCRmyPDF does work (not great, to be honest, the words are only partially correct, but hey, better than nothing) without issue.
PDFSandwich actually doesn't work from the command line anymore. Same fatal error as the one in Alfresco, so I should actually be looking at how to fix that program, if I wanted to use it.

**Comment by ninaran** [comment]
It does however still create the _ocr file, even though the error is present. 

![pdfsandwich_test](https://cloud.githubusercontent.com/assets/20947541/17586775/fe855e3a-5fc3-11e6-9c2a-bce621781eeb.JPG)

**Comment by angelborroy-ks** [comment]
We have not tested yet pdfsandwich 0.1.5.

We used 0.1.4 instead, you can download this version at [https://sourceforge.net/projects/pdfsandwich/files/pdfsandwich%200.1.4/](https://sourceforge.net/projects/pdfsandwich/files/pdfsandwich%200.1.4/)

**Comment by ninaran** [comment]
Ah yes, the 0.1.4 Version does work in the command line, same with OCRmyPDF.

![ocr_tests](https://cloud.githubusercontent.com/assets/20947541/17588387/c89b1b10-5fce-11e6-8901-fc65bbedd88a.JPG)

I tried a new installation from scratch (just to be safe, and it's fast anyways; same process as above), using 0.1.4 now, but it's still not working. New error message, though: [catalina.out](http://pastebin.com/wJ6acJE6)

**Comment by angelborroy-ks** [comment]
We are near: which version are you using for `alfresco-simple-ocr`?

**Comment by ninaran** [comment]
The [German translation](https://github.com/keensoft/alfresco-simple-ocr/releases/tag/1.0.1) one.

**Comment by angelborroy-ks** [comment]
Use the last one: [https://github.com/keensoft/alfresco-simple-ocr/releases/download/1.1.0/simple-ocr-repo-1.1.0.amp](https://github.com/keensoft/alfresco-simple-ocr/releases/download/1.1.0/simple-ocr-repo-1.1.0.amp)

This 1.1.0 also includes German translation.

**Comment by ninaran** [comment]
Hm.. that one does not show up when I want to create a new rule for a folder. Though the alfresco-mmt.jar tells me that it's installed in the alfresco.war

**Comment by angelborroy-ks** [comment]
Copy the new one to `alfresco/amps` and perform `apply_amps.sh -force`

As is a greater version, Alfresco will install it over the new one. If you can't manage to uninstall / upgrade the addon, use a new Alfresco installation (you are becoming an expert on this)

**Comment by ninaran** [comment]
I thought a simple `java -jar alfresco-mmt.jar uninstall simple-ocr-repo /var/alfresco-community/tomcat/webapps/alfresco.war` would do the trick. But apparently not, so I did a quick re-install of the entire thing and used simple-ocr-repo-1.1.0.amp now and it's working!

First, thank you **so** much for all your time, I really appreciate it.

And second to recap. use PDFSandwich 0.1.4 and simple-ocr-repo_1.1.0, no other combination.

**Comment by angelborroy-ks** [comment]
Thanks for your time and patience.

We'll try to make some compatibility tests in the future, but yours is a good feedback for future users.

**Comment by LuisBenji** [comment]
Can i use  PDFSandwich in Alfresco 5.2.1?

**Comment by angelborroy-ks** [comment]
It should work, since I haven't tested it yet.
